"""Cloud-neutral S3-compatible implementation of the private media boundary.

This adapter intentionally uses only the standard S3 API surface supported by
AWS S3, Cloudflare R2, Backblaze B2, MinIO, and comparable providers.
"""
from __future__ import annotations

import asyncio
import hashlib
from datetime import UTC, datetime
from typing import Any

from ..config import Settings
from ..errors import MediaUnavailableError
from .media_service import PresignedUpload, StoredObject


class S3CompatibleMediaStorage:
    """Private-bucket storage; object keys are generated by ``MediaService``."""

    def __init__(self, settings: Settings) -> None:
        # Import only in the explicitly enabled S3 path. A local-only API
        # remains startable without the optional S3 client dependency.
        import boto3
        from botocore.config import Config

        self._bucket = settings.media_s3_bucket or ""
        self._presign_seconds = settings.media_s3_presign_seconds
        self._prefix = f"{settings.media_object_prefix.strip('/')}/"
        config = Config(
            signature_version="s3v4",
            s3={"addressing_style": settings.media_s3_addressing_style},
        )
        session = boto3.session.Session(
            aws_access_key_id=settings.media_s3_access_key_id,
            aws_secret_access_key=settings.media_s3_secret_access_key,
            aws_session_token=settings.media_s3_session_token,
            region_name=settings.media_s3_region,
        )
        self._client = session.client(
            "s3",
            endpoint_url=settings.media_s3_endpoint_url,
            config=config,
        )

    async def create_upload_grant(
        self, object_key: str, mime_type: str, size_bytes: int, checksum: str
    ) -> PresignedUpload:
        self._require_private_key(object_key)
        headers = {
            "Content-Type": mime_type,
            "x-amz-meta-familyapp-sha256": checksum,
            "x-amz-meta-familyapp-size": str(size_bytes),
        }
        parameters = {
            "Bucket": self._bucket,
            "Key": object_key,
            "ContentType": mime_type,
            "Metadata": {
                "familyapp-sha256": checksum,
                "familyapp-size": str(size_bytes),
            },
        }
        url = await self._call("generate_presigned_url", "put_object", Params=parameters, ExpiresIn=self._presign_seconds)
        return PresignedUpload(url=url, headers=headers)

    async def verify_upload(
        self, object_key: str, mime_type: str, size_bytes: int, checksum: str
    ) -> bool:
        self._require_private_key(object_key)
        head = await asyncio.to_thread(self._head_or_missing_sync, object_key)
        if head is None:
            return False
        if int(head.get("ContentLength", -1)) != size_bytes:
            return False
        stored_type = str(head.get("ContentType", "")).split(";", 1)[0].strip().lower()
        if stored_type != mime_type.lower():
            return False
        metadata = {str(key).lower(): str(value) for key, value in head.get("Metadata", {}).items()}
        if metadata.get("familyapp-sha256", "").lower() != checksum.lower():
            return False
        if metadata.get("familyapp-size") != str(size_bytes):
            return False
        return await self._checksum_matches(object_key, checksum)

    async def object_exists(self, object_key: str) -> bool:
        self._require_private_key(object_key)
        head = await asyncio.to_thread(self._head_or_missing_sync, object_key)
        return head is not None

    async def delete(self, object_key: str) -> None:
        self._require_private_key(object_key)
        # S3 DELETE is idempotent: deleting a missing key is successful.
        await self._call("delete_object", Bucket=self._bucket, Key=object_key)

    async def create_download_url(self, object_key: str) -> str:
        self._require_private_key(object_key)
        return await self._call(
            "generate_presigned_url",
            "get_object",
            Params={"Bucket": self._bucket, "Key": object_key},
            ExpiresIn=self._presign_seconds,
        )

    async def list_objects(self, prefix: str) -> list[StoredObject]:
        normalized_prefix = f"{prefix.strip('/')}/"
        if normalized_prefix != self._prefix:
            raise MediaUnavailableError("invalid media storage prefix")
        return await asyncio.to_thread(self._list_objects_sync, normalized_prefix)

    async def _checksum_matches(self, object_key: str, checksum: str) -> bool:
        return await asyncio.to_thread(self._checksum_matches_sync, object_key, checksum)

    def _checksum_matches_sync(self, object_key: str, checksum: str) -> bool:
        body: Any | None = None
        try:
            response = self._client.get_object(Bucket=self._bucket, Key=object_key)
            body = response["Body"]
            digest = hashlib.sha256()
            while chunk := body.read(1024 * 1024):
                digest.update(chunk)
            return digest.hexdigest() == checksum.lower()
        except Exception as error:
            raise self._unavailable(error) from error
        finally:
            if body is not None:
                body.close()

    def _head_or_missing_sync(self, object_key: str) -> dict[str, Any] | None:
        try:
            return self._client.head_object(Bucket=self._bucket, Key=object_key)
        except Exception as error:
            if self._is_missing_object(error):
                return None
            raise self._unavailable(error) from error

    def _list_objects_sync(self, prefix: str) -> list[StoredObject]:
        objects: list[StoredObject] = []
        continuation: str | None = None
        try:
            while True:
                parameters: dict[str, Any] = {"Bucket": self._bucket, "Prefix": prefix}
                if continuation is not None:
                    parameters["ContinuationToken"] = continuation
                response = self._client.list_objects_v2(**parameters)
                for item in response.get("Contents", []):
                    key = str(item["Key"])
                    if not key.startswith(prefix):
                        continue
                    modified = item.get("LastModified")
                    if isinstance(modified, datetime) and modified.tzinfo is None:
                        modified = modified.replace(tzinfo=UTC)
                    objects.append(StoredObject(object_key=key, last_modified=modified))
                if not response.get("IsTruncated"):
                    return objects
                continuation = response.get("NextContinuationToken")
                if not continuation:
                    raise RuntimeError("truncated S3 list omitted continuation token")
        except Exception as error:
            raise self._unavailable(error) from error

    async def _call(self, method: str, *args: Any, **kwargs: Any) -> Any:
        return await asyncio.to_thread(self._call_sync, method, *args, **kwargs)

    def _call_sync(self, method: str, *args: Any, **kwargs: Any) -> Any:
        try:
            return getattr(self._client, method)(*args, **kwargs)
        except Exception as error:
            raise self._unavailable(error) from error

    def _require_private_key(self, object_key: str) -> None:
        if not object_key.startswith(self._prefix) or object_key.endswith("/"):
            raise MediaUnavailableError("invalid private media object key")

    @staticmethod
    def _unavailable(_: Exception) -> MediaUnavailableError:
        # Deliberately discard provider details: they can reveal bucket names,
        # endpoints, or signed request material in logs and API responses.
        return MediaUnavailableError("private media storage is unavailable")

    @staticmethod
    def _is_missing_object(error: Exception) -> bool:
        response = getattr(error, "response", None)
        code = str(response.get("Error", {}).get("Code", "")) if isinstance(response, dict) else ""
        return code in {"404", "NoSuchKey", "NotFound"}
